### ISSUE TITLE
Python error on line 96 and line 271

### ISSUE THREAD

**Issue by IltisGraph** [extinctsion/easyPythonpi#21]
When I open up the project in pycharm it shows some missing indents in line 96 and 271. Those issues are in the function matrix_mul and hex2bin.

**Comment by extinctsion** [comment]
@PreyumKr pls help with this issue. Check if there is any fault with the code. Thank you.

**Comment by extinctsion** [comment]
I hope, this issue is fixed now. closing this issue.
