### ISSUE TITLE
Convert the Python code according to the latest syntax.

### ISSUE THREAD

**Issue by extinctsion** [extinctsion/easyPythonpi#24]
Python has released its latest syntax for version 3.9x onwards. You can see the syntax in their doc section and convert the exisitng code into the latest version. Interested person can address me so that you are assigned the role.
Ex -> #def add(x,y) can be written as---

# def add(x: float, y:float) -> float:

This is the new syntax that we can use while defining a method.

**Comment by AndrewHUNGNguyen** [comment]
@extinctsion can I take this one?

**Comment by extinctsion** [comment]
> @extinctsion can I take this one?

Sure, but someone else already did. meanwhile,u can add new methods to the library. Also,  im planning to automate this library to pypi release.
