### ISSUE TITLE
Add a folder for test cases and add the files there.

### ISSUE THREAD

**Issue by extinctsion** [extinctsion/easyPythonpi#42]
Create a folder named "test_cases" and all the test cases files in that folder.

**Comment by AdityaDKale** [comment]
Can you assign me this issue?

**Comment by extinctsion** [comment]
@AdityaDKale already done by @vivekBoli.

**Comment by Ayushlion8** [comment]
Hey, I want to work on this issue:)

**Comment by extinctsion** [comment]
@Ayushlion8 pls refer to comment in PR - Add a folder for test cases and add the files there. #42Organised File Structure #43 
and then proceed. thank you

**Comment by Ayushlion8** [comment]
Hey @extinctsion, you want me to create a "test_cases" folder and add all the files of python functions present in "easyPythonPi" folder

**Comment by extinctsion** [comment]
Thanks for the contribution. This issue is closed now.
