### ISSUE TITLE
Restructure the library and adjust the importing in each file

### ISSUE THREAD

**Issue by extinctsion** [extinctsion/easyPythonpi#55]
Note: The changes that are to be made is written in parentheses( )
##Fix the importing errors.
The error we are getting while importing the files - 

![Error](https://github.com/extinctsion/easyPythonpi/assets/67048929/e12caf5a-f0c5-4583-a269-1172dfb0568a)

The file structure that should be done - 
.github/workflows
easyPythonpi
        -----------methods
                           --------__init__.py
                           --------basics.py
                                        .
                                        .
       ------------test
                           ---------__init__.py
                           ---------test_basics.py
                           ---------test_linkedlist.py
                                        .
                                        .
      -------------__init__.py (if that's needed. If not dont include)
      -------------easyPythonpi.py (execution starts from here)

CONTRIBUTION.md  (Change name from contributing to contribution.md)
README.md
setup.py

If your are not sure about any file structure, feel free to ping in this channel.

**Comment by AndrewHUNGNguyen** [comment]
> @AndrewHUNGNguyen I have created the issue. Have a look -

@extinctsion 

What do I need to do after pulling the most up-to-date code? I looked through the readme, and I don't see any clear way to tell if the code is running as supposed to, especially the test cases.

**Comment by extinctsion** [comment]
@AndrewHUNGNguyen readme is also outdated. Don't follow that. First we have to make a working library then we can write readme according to that code.

**Comment by AndrewHUNGNguyen** [comment]
> @AndrewHUNGNguyen readme is also outdated. Don't follow that. First we have to make a working library then we can write readme according to that code.

Gotcha! A followup question that I have is how should I reproduce the steps to the error in the screenshot? I forgot to ask you to provide the steps to reproduce. The only thing I will have to figure on my own is how to do it on Mac I guess, since you got this error in a Windows Environment.

**Comment by AndrewHUNGNguyen** [comment]
@extinctsion actually I think I reproduced the steps via Mac, not sure if this is the exact error.
<img width="901" alt="Screenshot 2023-10-08 at 5 31 22 AM" src="https://github.com/extinctsion/easyPythonpi/assets/42189273/29c50b1a-8318-4e35-bb7c-ad6a20c8064f">

**Comment by extinctsion** [comment]
Come out of the test_cases dir. Then try again. Are u getting same error?

**Comment by AndrewHUNGNguyen** [comment]
> Come out of the test_cases dir. Then try again. Are u getting same error?
<img width="893" alt="Screenshot 2023-10-08 at 6 06 59 AM" src="https://github.com/extinctsion/easyPythonpi/assets/42189273/51c801fd-a3de-495a-b202-c41dac727638">

**Comment by extinctsion** [comment]
Run command - python -m unittest

**Comment by extinctsion** [comment]
If it works then the structure for test cases is now ok.

**Comment by AndrewHUNGNguyen** [comment]
> python -m unittest

<img width="605" alt="Screenshot 2023-10-08 at 6 19 26 AM" src="https://github.com/extinctsion/easyPythonpi/assets/42189273/40b1460f-8576-420a-a285-fe6ff4797b02">

**Comment by extinctsion** [comment]
@AndrewHUNGNguyen I'm also trying to figure out a solution.

**Comment by extinctsion** [comment]
![image](https://github.com/extinctsion/easyPythonpi/assets/67048929/db41e21a-e307-4e9c-a48d-5a0e644e9379)
Hey! I'm very excited to tell that I have fixed that issue and also released new build on pypi.org. Now everyone can download new release and enjoy! Closing this issue now
