### ISSUE TITLE
Group Operations into Separate Files

### ISSUE THREAD

**Issue by AndrewHUNGNguyen** [extinctsion/easyPythonpi#64]
As a developer maintaining the repo, I want to categorize the operations out for easier understanding and maintenance of files. Current string operations, bitwise operations, and statistical operations should be separated from basics.py into their own files (e.g. have a file dedicated to string operations, another file for bitwise operations, and another for statistical operations)

**Comment by extinctsion** [comment]
Sure, go ahead.

**Comment by AndrewHUNGNguyen** [comment]
> Sure, go ahead.

Created a PR at #65

**Comment by extinctsion** [comment]
This issue is now resolved as I have merged the PR.
