### ISSUE TITLE
Let's make a githubworkflows action to test cases whenever a new pull request is made.

### ISSUE THREAD

**Issue by extinctsion** [extinctsion/easyPythonpi#67]
A github workflow actions can be made to check the test cases whenever a new pull request is made on the main branch. 

This will entirely automate the process and we can restrict the pull request or ask them to make necessary changes whenever they fail any test cases.

Feel free to ask any questions if you have any doubt.

**Comment by Kishore-abhimanyu** [comment]
I would like to work on this. Can you please assign this to me?

**Comment by Kishore-abhimanyu** [comment]
Please review this [PR ](https://github.com/extinctsion/easyPythonpi/pull/70)

**Comment by extinctsion** [comment]
Also pls configure to test for various version of python from py3.7 to latest and also on different platforms such as windows, ubuntu latest and mac.

**Comment by extinctsion** [comment]
you can take help from this youtube video - https://youtu.be/UEOtZvTCmDo?si=SwfdqnLw-3isB8P3

**Comment by Kishore-abhimanyu** [comment]
@extinctsion I have made the required changes. Please verify 
<img width="1379" alt="Screenshot 2023-10-22 at 5 11 12 PM" src="https://github.com/extinctsion/easyPythonpi/assets/72184554/0a75804d-9fb1-48c2-94c7-997273110ddf">

**Comment by extinctsion** [comment]
This workflow is working fine. Hence, this issue is resolved.
