### ISSUE TITLE
Defects in is_palindrome() and remove_punctuation()

### ISSUE THREAD

**Issue by AndrewHUNGNguyen** [extinctsion/easyPythonpi#68]
is_palindrome() fails test cases where the string is a sentence with the same characters.

remove_punctuation() fails on unicode punctuations like © and ™. We may need to include unicode characters as punctuations to remove as well listed at https://www.compart.com/en/unicode/category/Po

@extinctsion let me know your thoughts on punctuations we need to include.

**Comment by AndrewHUNGNguyen** [comment]
@extinctsion assign this issue to me.

**Comment by extinctsion** [comment]
I think it's practically impossible to include all unicode punctuations as one may create custom using their own unicode. Hence, it would be better to only include those punctuations which are frequently used.

**Comment by AndrewHUNGNguyen** [comment]
@extinctsion in case you want to modify is_palindrome only, I created a PR at #75

**Comment by AndrewHUNGNguyen** [comment]
@extinctsion I created a PR at #76

**Comment by extinctsion** [comment]
Thanks. Merged it in the main branch.
Now if you will raise any PR, it will test for all the test cases and then it will be approved for merge.

**Comment by extinctsion** [comment]
issue resolved
