### ISSUE TITLE
Create a File Containing Geometric Formulas

### ISSUE THREAD

**Issue by AndrewHUNGNguyen** [extinctsion/easyPythonpi#69]
Create a file that stores all geometry formulas calculating the perimeter, area, and volume of various shapes.

@extinctsion feel free to share your thoughts on this.

**Comment by AndrewHUNGNguyen** [comment]
@extinctsion if you think this is a good issue assign this to me.

**Comment by extinctsion** [comment]
Yes, methods relating to mensurations and geometry should have their own class. Pls make their classes and inside them you can include their methods.

**Comment by AndrewHUNGNguyen** [comment]
Created a PR at #79

**Comment by extinctsion** [comment]
https://github.com/extinctsion/easyPythonpi/pull/83
I think this PR was merged and resolved the issue. Hence, closing this issue
