### ISSUE TITLE
Adding Black and Isort to maintain the repository by following python conventions

### ISSUE THREAD

**Issue by Kishore-abhimanyu** [extinctsion/easyPythonpi#71]
Adding Black and Isort to maintain the repository by following python conventions

**Comment by Kishore-abhimanyu** [comment]
@extinctsion If you think, this as a needed feature, please assign the issue to me. Would like to work on this issue

**Comment by extinctsion** [comment]
Can you explain a bit what is isort and black for maintaining this repo?

**Comment by extinctsion** [comment]
Pls help us identify the requirements then I'll assign you this issue.

**Comment by Kishore-abhimanyu** [comment]
I can see that the files are not intended properly and some are violating
python standing spacing policies. When we add black to the project we can
make sure that it is following those standards and we can also add a check
in GitHub actions. What do you think?

**Comment by extinctsion** [comment]
Still not clear 😅. Can you give some links to read and understand or have u implemented it before? Pls share it here.

**Comment by Kishore-abhimanyu** [comment]
Sure. Find the link below
https://pypi.org/project/black/

**Comment by extinctsion** [comment]
Yea, I also searched about it and I think it should be include in this repo. Thanks for giving such amazing idea.

**Comment by Kishore-abhimanyu** [comment]
You're welcome! Please assign me this issue. I will start to work on it

**Comment by extinctsion** [comment]
Sure.

**Comment by Kishore-abhimanyu** [comment]
Added the PR https://github.com/extinctsion/easyPythonpi/pull/74, please review

**Comment by Kishore-abhimanyu** [comment]
Also, can you please add hacktoberfest label to it

**Comment by extinctsion** [comment]
This PR has been merged hence closing this issue
