### ISSUE TITLE
Fix failing tests and format the files

### ISSUE THREAD

**Issue by Kishore-abhimanyu** [extinctsion/easyPythonpi#73]

**Comment by Kishore-abhimanyu** [comment]
Have added this PR https://github.com/extinctsion/easyPythonpi/pull/72

**Comment by Kishore-abhimanyu** [comment]
Also, can you please add hacktoberfest label to it @extinctsion

**Comment by AndrewHUNGNguyen** [comment]
@extinctsion you can find a pr relevant to bfs and dfs unit test fix at #80

**Comment by extinctsion** [comment]
We have fixed the issues and I hope this is resolved. Hence, closing this issue
