### ISSUE TITLE
Patterns Printing File 

### ISSUE THREAD

**Issue by AndrewHUNGNguyen** [extinctsion/easyPythonpi#84]
As a beginner to Python Programming or programming in general, I want to get a clear introduction to function/method calls in Python with pattern printing in python. Create a python file that will display the printout pattern when a pattern_printing method is called.  

Refer to https://www.geeksforgeeks.org/programs-printing-pyramid-patterns-python/ for an example.

**Comment by AndrewHUNGNguyen** [comment]
@extinctsion Take a look at this issue to see if this is what we have discussed.

**Comment by extinctsion** [comment]
Yes, this is as we discussed.

**Comment by AndrewHUNGNguyen** [comment]
@extinctsion i created a pr at #85

**Comment by extinctsion** [comment]
I think we have resolved this issue and we can mark it close
