### ISSUE TITLE
[Issue] Improve Version Management in setup.py

### ISSUE THREAD

**Issue by sadhiin** [extinctsion/easyPythonpi#92]
# Improve Version Management in setup.py

## Current Behavior
Our current `setup.py` doesn't consistently increment the version number, which can lead to conflicts when uploading to PyPI.

## Proposed Solution
Update `setup.py` to:
1. Fetch the latest version from PyPI
2. Increment the version number automatically
3. Incorporate git information when available

This will ensure that each new build has a unique, incrementing version number that's always higher than what's on PyPI.

## Benefits
- Prevents version conflicts with PyPI
- Automates version management
- Maintains compatibility with git-based versioning
- Works in both git and non-git environments

## Implementation Details
- Add functions to fetch PyPI version and increment version
- Modify `get_version()` to use these new functions
- Ensure compatibility with existing git-based versioning

## Additional Notes
- This change will require adding `requests` to the project dependencies
- We may need to update CI/CD pipelines to accommodate this change

**Comment by sadhiin** [comment]
@extinctsion 
Hi there, This was the issue previously on setup.py to getting the version number.  As it wasn't taking the tag number form git hub action.

Updated implementation 
- Previous github tag parsing option is there, in case it's not able to get the tag number form github.
- Use'request'` and call on pypi page of this project.
- Extract the current version number on pypi page.
-  Update the `major` . `minor` . `patch` number accordingly
- `if VERSION and "-" in VERSION:` added on line number 56 of `setup.py` file.

**Comment by extinctsion** [comment]
Shall I assign this to you? @sadhiin

**Comment by Psudopodiya** [comment]
## Improving Version Management in ` setup.py`

### 1. Fetch the Latest Version from PyPI

To check the current version of our package on PyPI, we'll can use a Python library to make a request to the PyPI API and fetch the version. This will help us increment the version later.

- need to make an HTTP request.
- can use a library like requests for this.
- parsing JSON responses to extract the version information. (optional and not sure about if this will be helpful)

```
response = requests.get("https://pypi.org/pypi/YOUR_PACKAGE/json")
version_info = response.json()['info']['version']
```

### 2. Increment the Version Number
Once we have the latest version from PyPI, we need to increment it. Usually, i'd increment the patch number (e.g., from 1.0.0 to 1.0.1).

- can split the version string into major, minor, and patch.
- After incrementing the patch, combine the version components back into a string.
```
major, minor, patch = version.split(".")
patch = str(int(patch) + 1)
new_version = f"{major}.{minor}.{patch}"
```

### 3.  Fetch the Version from Git (if available)
In case the code is in a git repository, we can use git tags to derive the version dynamically. Use a subprocess call to run a git command and capture the output.

```
version = subprocess.run(
    ["git", "describe", "--tags"],
    stdout=subprocess.PIPE
).stdout.decode("utf-8").strip()
```

### 4. Combine Git Versioning and PyPI
need to combine the two approaches. First, check if the code is in a git repository, and if a tag is available, use that. If not, fallback to using the version from PyPI.

- can set up a conditional: first try git, and if it fails, fetch the PyPI version.
- This will ensure that git-based and non-git-based environments are handled.
```
if git_version_available():
    version = get_git_version()
else:
    version = get_latest_pypi_version()
```
    
### 5. Set up the `setup()` Function
Once we have the final version, integrate it into the setup() function. This version number will now be dynamic, preventing manual mistakes and version conflicts.

- Pass the version variable to the setup() function.
```
setup(
    name="your_package",
    version=version,
    install_requires=["requests", ...]
)
```

### 6. Add a Fallback for Non-Git Environments
In case the package is being built in a non-git environment (like CI/CD pipelines), you’ll want a default version or a way to handle the absence of git information.

- Use a default version, like 0.1.0, when neither git nor PyPI is available.
- Ensure your code doesn’t crash if it can’t access git or the PyPI API.

```
version = get_version_from_git() or get_latest_pypi_version() or "0.1.0"
```

## Final Considerations

- CI/CD: might need to update your CI/CD pipeline to ensure the necessary libraries (like requests) are installed before running the build.
- Version Conflicts: This process helps prevent version conflicts by automating version management and ensuring that each new build gets a unique version.

**Comment by Psudopodiya** [comment]
> ## Improving Version Management in ` setup.py`
> ### 1. Fetch the Latest Version from PyPI
> To check the current version of our package on PyPI, we'll can use a Python library to make a request to the PyPI API and fetch the version. This will help us increment the version later.
> 
> * need to make an HTTP request.
> * can use a library like requests for this.
> * parsing JSON responses to extract the version information. (optional and not sure about if this will be helpful)
> 
> ```
> response = requests.get("https://pypi.org/pypi/YOUR_PACKAGE/json")
> version_info = response.json()['info']['version']
> ```
> 
> ### 2. Increment the Version Number
> Once we have the latest version from PyPI, we need to increment it. Usually, i'd increment the patch number (e.g., from 1.0.0 to 1.0.1).
> 
> * can split the version string into major, minor, and patch.
> * After incrementing the patch, combine the version components back into a string.
> 
> ```
> major, minor, patch = version.split(".")
> patch = str(int(patch) + 1)
> new_version = f"{major}.{minor}.{patch}"
> ```
> 
> ### 3. Fetch the Version from Git (if available)
> In case the code is in a git repository, we can use git tags to derive the version dynamically. Use a subprocess call to run a git command and capture the output.
> 
> ```
> version = subprocess.run(
>     ["git", "describe", "--tags"],
>     stdout=subprocess.PIPE
> ).stdout.decode("utf-8").strip()
> ```
> 
> ### 4. Combine Git Versioning and PyPI
> need to combine the two approaches. First, check if the code is in a git repository, and if a tag is available, use that. If not, fallback to using the version from PyPI.
> 
> * can set up a conditional: first try git, and if it fails, fetch the PyPI version.
> * This will ensure that git-based and non-git-based environments are handled.
> 
> ```
> if git_version_available():
>     version = get_git_version()
> else:
>     version = get_latest_pypi_version()
> ```
> 
> ### 5. Set up the `setup()` Function
> Once we have the final version, integrate it into the setup() function. This version number will now be dynamic, preventing manual mistakes and version conflicts.
> 
> * Pass the version variable to the setup() function.
> 
> ```
> setup(
>     name="your_package",
>     version=version,
>     install_requires=["requests", ...]
> )
> ```
> 
> ### 6. Add a Fallback for Non-Git Environments
> In case the package is being built in a non-git environment (like CI/CD pipelines), you’ll want a default version or a way to handle the absence of git information.
> 
> * Use a default version, like 0.1.0, when neither git nor PyPI is available.
> * Ensure your code doesn’t crash if it can’t access git or the PyPI API.
> 
> ```
> version = get_version_from_git() or get_latest_pypi_version() or "0.1.0"
> ```
> 
> ## Final Considerations
> * CI/CD: might need to update your CI/CD pipeline to ensure the necessary libraries (like requests) are installed before running the build.
> * Version Conflicts: This process helps prevent version conflicts by automating version management and ensuring that each new build gets a unique version.

This is one of the Documentation i prepared from another project's updating documentations. Not sure if it fit's best in this case but do let me know

**Comment by extinctsion** [comment]
Hi @Psudopodiya, can you work on this issue. Pls confirm and I'll assign this issue to you

**Comment by Psudopodiya** [comment]
Hi @extinctsion this is one of the docs i had on my project. For me to work on this might take around a week. please use recommend this to anyone who pops up in the meantime.
Will let you know as soon as I'm available

**Comment by sadhiin** [comment]
solved at PR #93

**Comment by extinctsion** [comment]
Though this ticket was closed, still we had some warning saying:
`[Build and publish Python 🐍 distributions 📦 to PyPI and TestPyPI](https://github.com/extinctsion/easyPythonpi/actions/runs/11524046439/job/32083362442)
The following actions use a deprecated Node.js version and will be forced to run on node20: actions/setup-python@v3. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/`

**Comment by sadhiin** [comment]
> Though this ticket was closed, still we had some warning saying:

Does it blocking to push like the previous time?

**Comment by extinctsion** [comment]
No. It is now working flawlessly. All thanks to you

**Comment by extinctsion** [comment]
Moreover, the in current scenario, existing pipelines was not able to deploy the latest release on PYPI, I had to configure some changes there(added git actions) as trusted publisher. then again ran the pipeline for smooth deployment
